version: 0.2

env:
  variables:
    JAVA_HOME: "/usr/lib/jvm/java-8-openjdk-amd64"
    AWS_ACCOUNT_ID: "841527033247"
    AWS_DEFAULT_REGION: "ap-southeast-2"
    IMAGE_REPO_NAME: "springrepo"
    IMAGE_TAG: "latest"

phases:
  install:
    runtime-versions:
      docker: 18
    commands:
    - echo installing maven...
    - apt-get update -y
    - apt-get install -y maven
  pre_build:
    commands:
    - echo Logging in to Amazon ECR... 
    - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
  build:
    commands:
    - echo building the userms
    - mvn install
    - echo Build started on `date`
    - echo Building the Docker image...
    - docker build -t $IMAGE_REPO_NAME:$IMAGE_TAG .
    - docker tag $IMAGE_REPO_NAME:$IMAGE_TAG $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG

  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG
      - printf '{"RepositoryName":"springrepo", "ImageURI":"%s", "ImageTags":["latest"]}' $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME > imageDetail.json 
artifacts:
  files:
    - '*.yaml'
    - '*.json'
  discard-paths: yes

cache:
  paths:
  - '/root/.m2/**/*'